<!DOCTYPE html>
<html>
<head>
    
   <title>Cargografías Acerca De</title>

    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/favicon.ico" type="image/x-icon" rel="icon" />
    <link href="/favicon.ico" type="image/x-icon" rel="shortcut icon" />

<link href='//fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
    
    <!-- V3 Styles -->

    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/new-timeline.css" type="text/css">
    <!-- V4 Styles -->
    <link rel="stylesheet" href="/css/flexboxgrid.min.css" type="text/css">
    
    <link rel="stylesheet" href="/css/cargo-base.css" type="text/css">
    <link rel="stylesheet" href="/css/animations.css" type="text/css">
    <link rel="stylesheet" href="/bower_components/wow.js/css/libs/animate.css" type="text/css">
    
    <!-- V2 Libs -->
    <script type="text/javascript" src="/js/lib/jquery-2.0.0.min.js"></script>
    <script type="text/javascript" src="/js/lib/underscore.min.js"></script>
    <script type="text/javascript" src="/js/lib/d3.min.js"></script>


    

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-18158765-5']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
    </script>

 

</head>
<body>
    <header>
        <div class="row">
            <div class="info col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    <div class="box">
                        <div class="row">
                            <div class="info col-xs-3">
                                <div class="logo box">
                                    <a href="/"><img src="/img/logo.png"></a>
                                </div>
                            </div>
                            <div class="info col-xs-9">
                                <div class="title box">
                                    <h1> Cargograf&iacute;as </h1>
                                    <p> La l&iacute;nea de tiempo de Pol&iacute;ticos Argentinos</p>
                                </div>
                            </div>
                        
                    </div>
                </div>
            </div>
            <div class="items col-xs-12 col-sm-4 col-md-4 col-lg-4">
                <ul class="instance-detail">
                    <li>
                        <i class="fa fa-map-marker"></i><span ng-cargo-loc="siteTitle"></span>
                    </li>
                    <li>
                        <i class="fa fa-globe"></i>Otros Paises</span>
                    </li>
                    
                </ul>
            </div>
            <div class="items col-xs-12 col-sm-2 col-md-2 col-lg-2">
                 <ul class="menu">
                    <li>
                    <a target="_blank" title="Sigue a @Cargografias en Twitter" href="https://twitter.com/intent/follow?original_referer=http%3A%2F%2Flocalhost%3A3000%2F&amp;region=follow_link&amp;screen_name=Cargografias&amp;tw_p=followbutton&amp;variant=2.0">
                        <i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="https://github.com/cargografias" target="_blank"><i class="fa fa-github"></i></a>
                    </li>
                    <li>
                    <a href="http://www.google.com/recaptcha/mailhide/d?k=01C7lOvjG_N7EaBpT3Yp2Lmw==&amp;c=so8gSuVp-5Xe2ocyAzNPdAZ8Uq5kd15DyhceyfZw3qY=" onclick="window.open('http://www.google.com/recaptcha/mailhide/d?k\07501C7lOvjG_N7EaBpT3Yp2Lmw\75\75\46c\75so8gSuVp-5Xe2ocyAzNPdAZ8Uq5kd15DyhceyfZw3qY\075', '', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300'); return false;" title="Reveal this e-mail address"><i class="fa fa-envelope-o"></i></a>
                    </li>
                    <li>
                       <a href="#"><i class="fa fa-cog"></i></a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </header>


    <div class="main">
        <div ng-view="" id="cargoContainer" class="ng-scope"><div class="module ng-scope">

        <div class="description">
            Acerca de Cargografias
        </div>
            <div class="content">
                <h1>Hola! </h1>
            </div>
        </div>
    </div>

    

    
</body>
</html>
