	<meta name="twitter:card" content="player">
    <meta name="twitter:site" content="@cargografias">
    <meta name="twitter:creator" content="@cargografias">
    <meta name="twitter:title" content="Cargografias - Politicos en el tiempo">
    <meta name="twitter:description" content="Cargograf&#237as es una linea de tiempo que muestra los cargos publicos que tuvo cada funcionario a lo largo de su vida. Entra y arma tu comparacion.">
    <meta name="twitter:player"property="twitter:player" 
    	content="{{shareUrl}}">
    <meta name="twitter:player:height" property="twitter:player:height" content="450">
    <meta name="twitter:player:width" property="twitter:player:width" content="438">
    